export enum KafkaEventEnum {
  USER_CREATED = 'user.created',
  LEGAL_REPRESENTATIVE_CREATED = 'legal-representative.created',
  LEGAL_REPRESENTATIVE_JURIDICAL_PERSON_DATA_SENT = 'legal-representative-juridical-person.data-sent',
  LEGAL_REPRESENTATIVE_JURIDICAL_PERSON_CREATED = 'legal-representative-juridical-person.created',
  LEGAL_REPRESENTATIVE_JURIDICAL_PERSON_CREATED_ERROR = 'legal-representative-juridical-person.created-error',
  LEGAL_REPRESENTATIVE_DELETE_SENT = 'legal_representative.delete-sent',
  LEGAL_REPRESENTATIVE_DELETED = 'legal_representative.deleted',
  LEGAL_REPRESENTATIVE_DELETED_FAILED = 'legal_representative.delete-failed',
  LEGAL_REPRESENTATIVE_CREATION_FAILED = 'legal-representative.creation-failed',
  LEGAL_REPRESENTATIVE_DOCUMENT_DELETED = 'legal_representative_document.deleted',
  LEGAL_REPRESENTATIVE_DOCUMENT_DELETE_FAILED = 'legal_representative_document.delete-failed',
  USER_CREATED_ERROR = 'user.created-error',
  USER_CREATE_DATA_SENT = 'user.create-data-sent',
  ONBOARDING_JURIDICAL_PERSON_CREATED = 'onboarding-juridical-person.created',
  ONBOARDING_JURIDICAL_PERSON_UPDATED = 'onboarding-juridical-person.updated',
  ONBOARDING_JURIDICAL_PERSON_DATA_SENT = 'onboarding-juridical-person.data-sent',
  ONBOARDING_JURIDICAL_PERSON_CREATE_DATA_SENT = 'onboarding-juridical-person.create-data-sent',
  ONBOARDING_JURIDICAL_PERSON_CREATED_ERROR = 'onboarding-juridical-person.created-error',
  ONBOARDING_JURIDICAL_PERSON_UPDATED_ERROR = 'onboarding-juridical-person.updated-error',
  LEGAL_REPRESENTATIVE_NATURAL_PERSON_DATA_SENT = 'legal-representative-natural-person.data-sent',
  LEGAL_REPRESENTATIVE_NATURAL_PERSON_CREATED = 'legal-representative-natural-person.created',
  LEGAL_REPRESENTATIVE_NATURAL_PERSON_CREATED_ERROR = 'legal-representative-natural-person.created-error',
  LEGAL_REPRESENTATIVE_UPDATE_DATA_SENT = 'legal-representative.update-data-sent',
  LEGAL_REPRESENTATIVE_UPDATED = 'legal-representative.updated',
  LEGAL_REPRESENTATIVE_UPDATED_ERROR = 'legal-representative.updated-error',
}
